### ISSUE TITLE
Dragging a viewbox locks the GM's Cursor in place.

### ISSUE THREAD

**Issue by Brimcon** [CDeenen/LockView#26]
After dragging a window to a new place either with the button or with right click with Edit Viewbox enabled, the GM cursor stops moving and only updates its position when moving the GM's view with right click.
To Reproduce:
Connect to the server with a second window, Move that Viewbox around, then watch the "Gamemaster" Cursor on the new window and compare with the mouse on the GM's window.
Only fix is to Refresh the GM's window

**Comment by CDeenen** [comment]
I was able to reproduce this. Not sure why it's happening, but I'll see if I can fix it.

**Comment by CDeenen** [comment]
Fixed in the latest release
