### ISSUE TITLE
View Box is displayed behind map tiles rather than on top of them

### ISSUE THREAD

**Issue by brother-oak** [CDeenen/LockView#36]
The view box seems to be displayed over the top of the background image, but behind any tiles that have been placed.
If you are using tiles instead of a background image, this means you cannot see the view boxes at all.

**Comment by CDeenen** [comment]
Thanks, I barely use tiles, so I hadn't noticed it. I'll have a look

**Comment by brother-oak** [comment]
Thanks :-)
It may become more of an issue for others, as I spotted it because I was setting up for an IRL game with a 'TV player' and creating a  very pretty map, using the quite recent Parallaxia mod to move backgrounds. That only works on tiles (not a background image) and can make really impressive battlemaps. But since I can't see (or edit) the view box, due to the whole background being tiles (it's a ship scene, and the whole background is a moving water tile), I can't use DM manipulation of the TV player map with your LockView mod.
But we aren't meeting up for a month, so I'm sure it'll be sorted by then ;-)

Cool mod, though - very useful for my IRL games that will start up again soon, COVID permitting!

**Comment by brother-oak** [comment]
I thought I'd see if there was an easy fix for this (pending a better one!) and it seems to work ok if you add the following line in the updateViewbox function of viewbox.js:

	this.zIndex = 100;

The viewbox seems to be displayed ok over tiles etc. It is also editable, moveable etc, so seems to work ok. However, I haven't stress tested it, nor is the number 100 particularly relevant - I just chose a big number!

Would be nice if this fix was included (if it doesn't break anything else!) in the next release, so I can use it on TheForge without having to upload my own version of the module.

**Comment by CDeenen** [comment]
Hey, thanks. I already solved this in my local version, but I was waiting for the release of Foundry 0.8.2 to make it compatible with 0.8. I'll probably push the next update in a few days.

**Comment by CDeenen** [comment]
This has been fixed in v1.4.7
