### ISSUE TITLE
player views keep going back to 'force initial view' during encounters

### ISSUE THREAD

**Issue by modzy2** [CDeenen/LockView#40]
Player views keep getting reset back to the 'force initial view' position when encounter is started by DM, or next turn pressed by DM, etc.  Founryvtt 0.7.9, lockview 1.4.8

**Comment by modzy2** [comment]
Thanks, it was happening earlier than 1.4.8

**Comment by CDeenen** [comment]
This should be fixed in the latest version (v1.4.9)
