### ISSUE TITLE
player views going back to forced initial view on a couple of other interactions (1.4.9)

### ISSUE THREAD

**Issue by modzy2** [CDeenen/LockView#42]
Sorry, I realise you've only just hours ago fixed the similar bug for when DM advances the encounter tracker (and thankyou, it is fine now), but just discovered these two more interactions which also set the player view back to the forced initial view.  These happened on 1.4.8 and also on 1.4.9
- if the DM resizes a token
- if a player left-click-drags the mouse trying to select a token, but they do not have access to that token
(also sometimes, but not always, if the player left-click-drags the mouse and there is no token at all in the selected area.)
- sometimes, not always, when the DM adds an actor to the encounter tracker via token hud

**Comment by modzy2** [comment]
Also, if the DM configures permissions for an actor (including one whose token is not on the map)

**Comment by CDeenen** [comment]
Thanks again for the report. I had already noticed some other instances where it would do that, and I thought I had fixed all of them, but I guess not :p.
I'll take a look at the instances you've mentioned, and I'll do a thorough search for others.

**Comment by dails08** [comment]
It also seems to happen on the following events:
- When the DM starts a song from a playlist
- Inconsistently, when the DM adjusts someone else's viewbox

**Comment by PedroCavati** [comment]
This also does happens whenever I select a tool from the sidebar.

**Comment by CDeenen** [comment]
Thank you all for your comments. Sorry that it took so long, and thank you for your patience. I believe this is fixed in the latest version that just got pushed. If not, please let me know.
