### ISSUE TITLE
Add option to remove sidebar completely

### ISSUE THREAD

**Issue by brother-oak** [CDeenen/LockView#43]
There is an option to collapse the sidebar upon activation, and another to remove the rest of the UI when the sidebar is collapsed, but no option to remove ALL UI elements (including the collapsed sidebar).
It would be useful to have an option to completely remove all UI elements upon scene activation.

**Comment by CDeenen** [comment]
In the latest version that just got pushed, I added a button in the scene configuration where you can set what UI elements to hide
