### ISSUE TITLE
Console error in foundry 0.8.5 

### ISSUE THREAD

**Issue by riccisi** [CDeenen/LockView#44]
I just wanted to point out that trying it on foundry version 0.8.5, it seems to work but keeps throwing this error in the console:

![CleanShot 2021-05-26 at 17 42 21](https://user-images.githubusercontent.com/6490765/119690196-c2802480-be49-11eb-90b4-6ebadc989b15.png)

![CleanShot 2021-05-26 at 17 43 15](https://user-images.githubusercontent.com/6490765/119690337-e04d8980-be49-11eb-8598-a522e8206492.png)

**Comment by CDeenen** [comment]
Thanks. It looks like it's trying to access the canvas when it's not yet initialized. Does it actually give issues, or is it just the error message?

**Comment by riccisi** [comment]
It seems to work, but I only use the lock pan, zoom and autoscale features. The error is thrown 11 times every time I open a scene for which I set lock pan and zoom to true and autoscale to Automatic Fit (inside) and it's just a little annoying, but maybe it could be a symptom of some malfunctions...

![CleanShot 2021-05-27 at 21 03 35](https://user-images.githubusercontent.com/6490765/119883070-67286200-bf2f-11eb-9a4f-203e2420db23.png)

**Comment by CDeenen** [comment]
I checked, and I don't think it gave any actual issues. It just tried to load some stuff before it should, I added some code to prevent that in the latest version that just got released.
