### ISSUE TITLE
v0.8.6 issue in console log

### ISSUE THREAD

**Issue by Jonwh25** [CDeenen/LockView#45]
seeing this in the console log for v0.8.6

![image](https://user-images.githubusercontent.com/60674327/120400829-88080300-c2f3-11eb-9a7a-544e63ca3de7.png)

**Comment by CDeenen** [comment]
Would you mind giving some more information?

Are you using the latest version of Lock View (v1.4.10)?
What game system are you on?
When does this occur (what combination of settings)?
What other modules do you have enabled?
Do you also get the error when you have no other modules enabled?

**Comment by Jonwh25** [comment]
I uninstalled and reinstalled 1.4.10 and now the problem seems to have gone away. 

Thank you. Feel free to close this out.
