### ISSUE TITLE
Module not working after update to 0.8

### ISSUE THREAD

**Issue by Naroek56** [CDeenen/LockView#50]
OS: Windows 10
Foundry version: 0.8.7
System: Old-School Essentials 1.2.2
Lock View: 1.4.11

None of the mechanisms, including "Lock Pan", "Lock Zoom" or " Bounding Box" work. The world is blank, there are are no other enabled modules and no error messages. 
Having all three of the above enabled and a player connected, they still can zoom out and pan out of canvas. 

The module worked perfectly fine before the update.

**Comment by CDeenen** [comment]
It seems to be working fine for me, also in 0.8.7 and with Old-School Essentials. 
Could you make sure that you've enabled 'Control' in the 'User Configuration' for the player.

**Comment by Naroek56** [comment]
Ah, I see. It must have reset that setting after update?
Either way, that was the missing piece, sorry for the confusion and thanks for the help :)

**Comment by CDeenen** [comment]
It shouldn't have reset, so that's a bit weird. Please let me know if that happens again.
