### ISSUE TITLE
[BUG] UI hiding feature incompatible with other modules that hide UI elements

### ISSUE THREAD

**Issue by sPOiDar** [CDeenen/LockView#52]
**Setup**
 - OS: Linux
 - Browser: Chrome
 - Module version: 1.4.12
 - Foundry version: 0.8.8
 - Gaming system & version: dnd5e 1.4.1
 - Any other modules enabled: yes

**Describe the bug**
If another module wishes to hide UI elements, Lock View will forcably unhide them, unless every scene is explicitly configured to hide those elements, however this is not sufficient in the case where UI elements are conditionally hidden by another module. For example, my Stream View module only hides UI elements for a specific user, and does so regardless of scene - it does not seem possible for me to allow this behaviour when Lock View is enabled.

**Additional context**
The `setUI()` function probably needs to be more intelligent about when it performs `.show()` on elements.

**Comment by CDeenen** [comment]
Thanks for reporting this issue.

I've done 2 things that should improve compatibility with Stream View:
1: Lock View will only unhide UI elements that have been configured to be hidden by Lock View.
2: Lock View checks if Stream View is enabled and if certain elements have been configured to show in Stream View, Lock View will not hide them

It will be added to the next Lock View update. Let me know if this solves your issue and whether you have any other ideas.

**Comment by sPOiDar** [comment]
That sounds like generally the right direction to me. though I have some notes:

For `1`, I think the logic on probably needs to be something like:
- On the `hide` path:
  - If the element is not configured for hiding by Lock View, abort
  - If the element is not currently visible, abort
  - Hide the element, and track that this element was explicitly hidden by Lock View
- On the `show` path:
  - If the element was not previously explicitly hidden by Lock View, abort
  - Show the element
By tracking whether Lock View was responsible for hiding the element, it should be possible to avoid unintentionally unhiding them.

As for `2` I think I'm actually fine with elements being hidden for the stream user if they're configured as such in Lock View, this seems like good functionality for splash screens or similar - all I'd like to avoid is having elements shown when they should not be. Not implementing `2` would also remove the need for coupling between the modules, and reduce future maintenance for you.

**Comment by CDeenen** [comment]
This should be fixed now
