### ISSUE TITLE
[BUG] Unable To Change Default Drawing Configuration

### ISSUE THREAD

**Issue by Dalsie** [CDeenen/LockView#54]
Module cannot function because unable to change the configuration from "Disabled".
It always defaults back to disabled.

![BugR](https://user-images.githubusercontent.com/22501546/130325688-2d512369-9db6-4fdf-b069-a3408c157312.jpg)

Tested on multiple browsers

**Comment by CDeenen** [comment]
Hey, I can't replicate this bug.
What Foundry version and system version are you on?
Do you also get this issue when you disable all other modules?

**Comment by CDeenen** [comment]
Closed due to a lack of a response
