### ISSUE TITLE
player view resetting autoscale during sidebar interactions/changes

### ISSUE THREAD

**Issue by modzy2** [CDeenen/LockView#59]
**Setup**
 - OS: windows
 - Browser: chrome
 - Module version: 1.4.14
 - Foundry version: 0.8.9
 - Gaming system & version: dnd5e 1.4.3
 - Any other modules enabled: no

**Describe the bug**
player has chat tab active, scene is activated with autoscale, and player changes their view, the players' view is often reset to the starting view when some interaction happens in the sidebar, 
Examples: 
music stops or starts or advances to next track
DM creates an item or item folder (even if something not visible to the player etc)
DM creates a journal or journal folder
DM creates an encounter

**Comment by CDeenen** [comment]
This should be fixed with the latest update
