### ISSUE TITLE
[FEATURE] Add option to enable control for all players in User Configuration

### ISSUE THREAD

**Issue by Mordecai007** [CDeenen/LockView#60]
We do a west marches style campaign where our Foundry world sees a lot of unique players coming through. We use The Forge's game manager which manages user accounts for us so each of these players comes in with a unique player account. It is frustrating to have to go to the settings to find their name and check off control for individual accounts when the true intention is to have it control all player accounts. I suggest creating an option to enable control for all players, perhaps also divided by account type (player, gm, etc.). This would make it so that when a new player account joins it is automatically added to the control list without a bunch of fussing around. We keep the Viewbox turned off, so a separate option for that to ensure it stays off for all players would also be a good idea.

**Comment by CDeenen** [comment]
I've added an override section in the User Configuration where you can override the Control and Viewbox for all users with a specific user role. Let me know if this doesn't solve it for you.
