### ISSUE TITLE
Black canvas in FVTT v9

### ISSUE THREAD

**Issue by DM-miX** [CDeenen/LockView#64]
I guess the v9 canvas updates are to blame here.
But with lock view the only module loaded the canvas is black

**Comment by joshscorcher** [comment]
Having similar issue.
![image](https://user-images.githubusercontent.com/52643998/146879808-8ca4d78a-0b79-4897-b1f1-49ac28ad3cfa.png)

**Comment by CDeenen** [comment]
Yeah, the module isn't V9 ready yet. I'm hoping to do that in the next week or so.

**Comment by Zaazka** [comment]
That's awesome news. Thanks for letting us know.

**Comment by CDeenen** [comment]
Lock View has been updated and should now work on v9
