### ISSUE TITLE
[FEATURE] Force initial view on user token when loading a scene

### ISSUE THREAD

**Issue by p4535992** [CDeenen/LockView#65]
**Is your feature request related to a problem? Please describe.**

No relation to any issue just something uùi think can be useful  on the logic of the module.

**Describe the solution you'd like**

During the load of the scene search on canvas for a token connected to the actor connected to the current user and force the initial view on to it similar to this macro

```
const actorName = game.user.character.name;
const entry = canvas.tokens?.placeables.find(token => token.document.actor.name === actorName);
canvas.animatePan({ x: entry?.token?._object?.x, y: entry?.token?._object?.y })
```

an center the visual zoom on that token (if present).

_Additional feature:_

If the token is not present create the token in the 'Initial view' box of the scene setted with the module setttings 'Force initial view'

**Describe alternatives you've considered**

The module https://github.com/SDoehren/always-centred has done something similar , but i will prefer to have all integrated in this module.

**Additional context**

**Comment by CDeenen** [comment]
I'm a bit confused about what this is supposed to do.
Normal Foundry behavior is to center on the user's token on scene load, if there's no such token it'll default to the scene's initial view.
If I understand you correctly, you're trying to get that functionality as part of Lock View, but if you disable 'force initial view' it should do that already, right?
