### ISSUE TITLE
[BUG] Lock Pan/Zoom don't work with Autoscale enabled

### ISSUE THREAD

**Issue by yjeroen** [CDeenen/LockView#67]
**Setup**
 - OS: Windows
 - Browser: Chrome
 - Module version: 1.5.0
 - Foundry version: 9.242
 - Gaming system & version: Symbaroum
 - Any other modules enabled: yes

**Describe the bug**
Lock Pan and Lock View are not working unless I put Autoscale on off

**Screenshots**
![image](https://user-images.githubusercontent.com/1303988/150642715-e79aff31-20df-426c-a85a-8ff203fb81db.png)
![image](https://user-images.githubusercontent.com/1303988/150642626-089b9f50-1eb6-477e-b62c-f76bc61f2d0f.png)

**Console Log**
No console errors/warnings.

**Comment by CDeenen** [comment]
Sorry for the late response.
I am able to reproduce this. What does work is toggling the locks off and on using the control buttons.
It looks like it doesn't initialize properly on scene load. I'll look into it.

**Comment by KammaKhazi** [comment]
Hi, I've just tried this on the latest version v1.5.2 it's working fine for me and tested my players accounts also....all good. I'm using the auto fit settings and locking both pan and zoom for my landing page.
