### ISSUE TITLE
Can't get autoscaling to work

### ISSUE THREAD

**Issue by AJAnderson** [CDeenen/LockView#7]
I've set the client screen size.

I've set enabled it in the client

I've set the grid size to be 100 px, and the scene size to be a multiple of that equivalent to my screen size (1900 pixels -> 19" wide screen).

No matter what I do (even if I change the client screen size to something crazy) the autoscale dialog does not appear to trigger any behaviour whatsoever.

**Comment by CDeenen** [comment]
I'm not sure if we solved this on Discord or not, but since I can't reproduce the issue and I haven't heard back from you I'll close it
