### ISSUE TITLE
 browser went into darkness

### ISSUE THREAD

**Issue by stalker168** [CDeenen/LockView#70]
**Setup**
 - OS: Windows 10
 - Browser: Chrome
 - Module version: 1.5.0
 - Foundry version: V9
 - Gaming system & version: dnd5e 1.5.7
 - Any other modules enabled: yes

**Describe the bug**
I had a problem with the fact that during the game after a while the graphic part of the browser went into darkness. Looking for a problem and came to the conclusion that the Lock View module is involved in this. It looks like it tries to take more and more RAM/GPU/CPU till the browser breaks

**Additional context**
The problem begins to be noticeable only during the game with the players.

**Comment by CDeenen** [comment]
Thanks for your bug report.
I haven't encountered this, or heard anyone else complaining about it. I don't know what could be causing it, maybe it's Lock View in combination with another module?
Right now I don't even know where to start with this.

**Comment by stalker168** [comment]
> Perhaps this problem occurs in conjunction with other modules, but when disabling Lock View, I no longer had a browser graphics crash. And the problem arose only during the game, when there were players on the server. There was no problem on their end.

**Comment by CDeenen** [comment]
Are you still experiencing this, or have you found some other cause or maybe some pattern that causes this?

**Comment by stalker168** [comment]
I last my treatment, I decided to stop using this module. Since then, only 3 gaming sessions have passed in which there was no longer the previously mentioned problem.

**Comment by CDeenen** [comment]
I will close this issue for now, if it happens again, please let me know.
