### ISSUE TITLE
[BUG] User Configuration no longer opens dialogs

### ISSUE THREAD

**Issue by r-valyar** [CDeenen/LockView#72]
**Setup**
 - OS: Windows 10, macOS 12.x
 - Browser: Firefox latest, MS Edge latest, Chrome
 - Module version: 1.5.1
 - Foundry version: 9.255
 - Gaming system & version: ALL systems
 - Any other modules enabled: Tinu UI

**Describe the bug**
On press "User Configuration" nothing happens. I am unable to configure users. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63558984/159516751-1d25d0c5-0ed0-4a29-9cee-c15a75358b1f.png)

**Console Log**
![image](https://user-images.githubusercontent.com/63558984/159516868-1bb81be9-aeb4-4557-9c72-d8c3618f6094.png)

**Additional context**
This worked couple of days ago. I presume something in the last u pdate.

**Comment by CDeenen** [comment]
Oops, I forgot to check for some conditions with some new code I added in the last update.
I've fixed it, but there appear to be some issues with the github server, so I can't upload it. I'll try again in a bit.

**Comment by r-valyar** [comment]
Works like a charm now. Thanks for the prompt fix!
