### ISSUE TITLE
Documentation, naming and UI are exceptionally confusing, massively hindering first-time users 

### ISSUE THREAD

**Issue by EvilRenegade** [CDeenen/LockView#73]
I have a GM-account.
I have a separate tabletop-account, which is who is logged in on the TV.
I want to control the view of the tabletop-account with my GM-account.

One would think that would be easy, considering that's what this module is all about.
But it just took me an hour to get the basic functionality to work, and the tabletop-user still has individual control over pan and zoom. I don't know if that's by design (e.g. either all zoom is locked or none), or if I just didn't set it up right.

Here are some of the problems I encountered:

I could find no definition what the checkbox "Control" in the user settings actually _does_. What specifically changes for the user if that checkbox is checked?
I could find no definition what the checkbox "Viewbox" in the user settings actually _does_. What specifically changes for the user if that checkbox is checked?

The text above the user settings says 

> Select which users the module can control and for what users the viewbox should be enabled.

The module description says

> Viewbox: Allows the GM to see what's shown on players screens, and allows the GM to control the pan and zoom of those players

So. I want the tabletop-account to be controlled and I want the GM-account to see what the tabletop-account sees. So I'm checking "Control" on the tabletop-account (-> I select it is a user which is controlled by the module) and "Viewbox" on the GM-account (-> it is an account who gets the GM viewbox feature), right?

> No connected and enabled clients on this scene.

Okay then.

What else does the documentation say?

> The viewbox is a function that allows the GM so see what users can see.
> If enabled (enable for the user in the User Configuration screen in the module settings, and enable the 'Viewbox' control button), a rectangle is drawn that corresponds with the view of the user.

Okay. So the viewbox is definitely a GM feature, so clearly checking "Viewbox" on the GM-account is correct. So why isn't it working?

> In the module settings, as a GM you will find a button to open the user configuration screen, where you can enable control and viewbox for each user. By default, both are enabled for non-GM users.
> Control must be enabled for each user if you want to use any of the functions of this module, except for displaying the viewbox, which has its own enable setting.

Wait, what? Do I have to check "Control" on _all_ users?
Well, I guess that makes sense...the GM account does interact with both sides of the module - it alters the viewport of the tabletop and draws the viewbox for the GM. So it needs control of both accounts.
But then...why are both checkboxes set to enabled for non-GM users?
That makes no sense!
If everybody needs to be controllable by the module and the GM needs the separate viewbox function, it should be two for the GM and one for everybody else, not none for the GM and two for everybody else!

Also, if it has to be enabled for all users anyway, why is it not just...enabled?
Why can an invalid state be created in the first place (by not having each user controllable) and why is that invalid state the default state?

> Besides enabling control and viewbox for each specific user, you can also override this and enable them based on their user role.

So it..._doesn't_ have to be enabled for each user, like the sentence immediately preceding it said?
??????
What?

> Enable the module and viewbox for the player that is connected to the TV in the User Configuration screen
> [...]
> In the User Configuration screen, enable the module and viewbox for each player whose view you want to control/view.

Okay.
So despite the fact that "viewbox" is only ever mentioned in a GM context, it's not the GM setting. Alright then. That's helpful.
And what exactly does it mean when it says "enable the module in the User Configuration screen...for each player"?
a) I can't do that anywhere. There's no button for that.
b) I wouldn't have the User Configuration screen if the module weren't enabled.

So...where do I stand?
I have a checkbox "Control".
I have a checkbox "Viewbox".
It tells me to _Select which users the module can control and for what users the viewbox should be enabled._
In practice, it seems "Control" means "control _of_ the viewbox", while "Viewbox" means "controlled _by_ the viewbox".
Stupid naming, but okay. Let's try it that way.

> Viewbox is disabled

Hmm. Apparently not. So I _do_ need the viewbox setting on the GM account to enable the viewbox feature for the GM.
Makes sense.
But then why does the documentation say..................????

After that point, it took me at least another ten minutes to figure out that "Viewbox is disabled" does not actually mean "the setting 'Viewbox' is currently disabled for this account" but rather "the viewbox is not currently displayed on this screen, so you cannot edit the viewbox".

**The nomenclature, the documentation and the error messages of this module are exceptionally confusing.**
It should not have taken this long to set two checkboxes and resize a box.

**Proposed fixes:**

- Clarify the term "viewbox". Define it clearly and use it for _one_ thing: Either the drawn box that represents the GM control mechanism, or the computer box that displays the player view.
- Change the naming of "Control" and "Viewbox" in the User Configuration settings. Communicate intent. Something like "Control View" and "Display User" could work.
- Change the description in the user configuration window, so that it properly tells the user what he's supposed to do. The phrasing "select which users the module can control" is extremely misleading when "Control" is actually the checkbox that _doesn't_ mean the user can be controlled.
- Change the error message "No connected and enabled clients on this scene." to be more helpful in solving the issue. When you're setting up the module and it's entirely unclear what you even have to enable, the phrasing of "no enabled clients"  misleads you into thinking you didn't get your checkboxes right. In reality, in my case, the "viewbox" session needed a page reload to rejoin after the settings had changed.
- Do away with the "Viewbox is disabled" scenario. It's a massively unhelpful and misleading error message. Instead, conditionally display the "edit viewbox" button only after the viewbox has been enabled. If that's not possible, disable the button while the viewbox is disabled and give it some sort of hover text, message box or whatever telling the user the viewbox needs to be enabled in order to be editable.
- Update the documentation. It's actually in the top quarter of software documentations I've read. Do keep the general approach and outline. It just needs to be less confusing in regards to the terms used and the actual _how_ of doing certain things.
- Deal with the "Enable the module [...] in the User Configuration settings" instruction. It's still not clear to me what that's supposed to mean or how I could enable the module in the module's settings if the module were disabled.

Please don't get me wrong: I do appreciate your effort and I'm thankful you're investing your time and your brain into this module.
I do know that especially feature names are entirely clear to people who work on a project, because they named them that way and they have been working with them for ages.
I'm not questioning the value or the functionality of the module. I'm just trying to emphasize the perspective of a first-time user.

**Comment by CDeenen** [comment]
It took me some time to get around to this, I'm sorry about that.

I completely agree that improvements are necessary. It is sometimes difficult to step into the shoes of the average user to figure out what is and isn't clear, so I'm very grateful that you took the time to write this.
And while it shouldn't be the case, the documentation is often just an afterthought. This means that while the module evolves, the documentation lacks behind and might refer to things that have changed, or might miss information about new things.

Therefore, I have made some big changes to the documentation. First of all, I've moved the documentation to the wiki, which hopefully makes everything easier to navigate: https://github.com/CDeenen/LockView/wiki
I've gone through everything and have added extra descriptions where I thought it was necessary, and I've tried to be more consistent. Whenever something is discussed that requires a specific setting (like having 'Control' enabled), I've made this clearer.

Hopefully this improves things.

When I'm ready to release an update to the module, I'll also take a close look at all the text in the module, to see where it can be improved.

**Comment by EvilRenegade** [comment]
Thank you very much - the updates do help a lot!

While reading it over, there was one part that caught my eye: In the [Usage section, in the GM client setup](https://github.com/CDeenen/LockView/wiki/Usage#in-person-play), you say

> Enable 'Control' and 'Viewbox' for the player that is connected to the TV 

...is that actually correct?
I would've thought the TV user exclusively needed _Control_ enabled.

**Comment by CDeenen** [comment]
You are correct that it only needs 'Control', however, when playing on a TV, the ability for the GM to easily control the view is often important, so the players don't need access to a keyboard and mouse. This is which is what 'Viewbox' enables, because it not only draws the viewbox, but also allows manipulation of the viewbox (and therefore the view on the TV).
I've modified it slightly to hopefully make this clearer.

**Comment by EvilRenegade** [comment]
I just realized that I still had not fully grasped the meaning of those configuration settings.

Having had this realization, your previous descriptions and default settings do make a lot more sense, but they also generate a  new matter of confusion: In what situation would I _not_ want both kinds of control?
It seems like a Boolean thing to me: "Do I want this account to be controllable by Lock View? Yes or No?"

Could you extend the docs with examples as to which of the four options (False on both, true only on Control, true only on Viewbox, true on both) is appropriate for which situation?

**Comment by CDeenen** [comment]
In the vast majority of cases you'd want either both enabled or disabled, but there are some niche applications where you might want them separated.

For example if you have a stream user, which you use to stream/record your game from. You might want 'control' enabled for everyone so your landing page works properly, but you only want 'viewbox' enabled for the stream user so you can easily keep track of, and control what's on display on your stream.

Similar situations can occur in other situations where you have one special user. For example, combining in-person on a TV with online play for some remote users.

I'm not sure if this is something worth mentioning. For users who'd need it, it's probably obvious. Others might wonder why it's split up, but it doesn't really matter since they'd probably be able to configure it like they'd want to anyway.

**Comment by CDeenen** [comment]
I believe this can be closed. The documentation on GitHub and within the module have been improved, hopefully it is now less confusing.
