### ISSUE TITLE
Unable to Pan

### ISSUE THREAD

**Issue by Chaithi** [CDeenen/LockView#75]
Since upgrading to version 9, I have intermittently been unable to pan the view when viewing the view box for a player or on the initial view screen. Sometimes it works fine, other times it ignores my clicks. I have been unable to narrow down why this occurs.

**Comment by Chaithi** [comment]
Using the "Find the Culprit" mod, I disabled all mods except Lock View and issue persisted.

**Comment by Chaithi** [comment]
Ah, think I just figured it out. If the grid is outside of the play area, it is unable to be moved.

**Comment by CDeenen** [comment]
This is, I believe, something that Foundry does, and not necessarily a Lock View issue. Looks like this issue can be closed.
