### ISSUE TITLE
Force Initial View Point Not working

### ISSUE THREAD

**Issue by Senrith73** [CDeenen/LockView#76]
Players are still getting snapped to their Actor's token position rather than the Initial View Point I set, even when following instructions to turn off Autoscale.

(Running version 9 Build 255 with no other modules active.)

**Comment by CDeenen** [comment]
I recently noticed the same, so I'll have to take a look at that.

**Comment by Senrith73** [comment]
Any luck so far?

**Comment by CDeenen** [comment]
When working on the last update, I wasn't able to reproduce it anymore, so I'm not sure what's going on.

**Comment by Senrith73** [comment]
Do you mean you wasn't able to reproduce the error?
It still isn't working for me. If there is a token on the canvas which a player has control of, their view will be centered on the token and not the Forced Initial View Point.

**Comment by CDeenen** [comment]
Yeah, previously I had the same problem, but not anymore. I tried it again earlier today while working on the new update, but it's functioning like it should.
Would you mind disabling all other modules to make sure that it's not a module incompatibility?

**Comment by Senrith73** [comment]
I disabled all modes except Lock View and it does still persist. 
I make sure to test with two browers. One joining as DM for which it works as normal, The Initial View point is the same, with or without Lock View.

Then I join with a Player and their view always goes to the owned token.

**Comment by CDeenen** [comment]
I just double checked on both Foundry v9 and v10, and still no issues.

Could you please double check your settings: 
-module settings =>user configuration => make sure 'enable' is checked for the user
-scene config => lock view => make sure 'force initial view' is checked and 'autoscale' is set to either 'off' or 'physical gridsize'
-scene config => basics => make sure 'initial view position' is not zero

If it's still not working:
What browser, operating system, foundry version and gaming system are you on?
Do you get any errors in the console (press F12 on the player browser, make sure you're on the console tab, errors show up in red).

**Comment by Senrith73** [comment]
Oh that's weird, it undid my settings for Enabled. Thanks it works now.

**Comment by CDeenen** [comment]
Good to hear that it works now.
Let's assume for now that it was a weird one-off thing, but if it happens again please let me know.
