### ISSUE TITLE
Add ability for players to lock view/pan

### ISSUE THREAD

**Issue by mwedel255** [CDeenen/LockView#78]
In our group, we are using a horizontal mounted TV, with miniatures on top.
In order to help offload the DM, one of the players is responsible for the map projected on this TV (scaling and moving as needed)
A problem is that the players can often do an option that results in the map panning for some reason.  Lockview fixes this, but this requires the DM to enable & disable the locking, and DM already has enough to deal with (even though this is pretty simple).  And in many cases, the DM himself may not want to lock their view.
I know with permissions, things can be set up so that lockview only applies to users of a certain role.  My thought here would be to change it so that Lockview only applies to the trusted player, have that player be the one controlling the screen, and have the lockview controls show up for that player.  In that way, the one controlling the screen can lock when combat starts, then unlock when combat finishes, etc, and not need to involve the DM in this.
This looks like it might be as simple as modifying the check that makes the controls visible, though I'm not sure that is the right approach.

**Comment by CDeenen** [comment]
This has been added in the last update (v1.5.3)
