### ISSUE TITLE
[BUG] Error Message during initialization

### ISSUE THREAD

**Issue by wickermoon** [CDeenen/LockView#79]
**Setup**
 - OS: win10
 - Browser: chrome
 - Module version: 1.5.3
 - Foundry version: 10.283
 - Gaming system & version: dnd5e 2.0.1
 - Any other modules enabled: yes

**Describe the bug**
When loading a world, LockView throws several errors/exceptions. As far as I can tell, LockView works, but when trying to migrate to foundry v10 it's making migration harder and I'm pretty sure errors/exceptions shouldn't be thrown during initialization.

**Screenshots**
![image](https://user-images.githubusercontent.com/15907070/187981466-21c38a44-02cd-47cf-9174-c5cff65838c1.png)

**Comment by wickermoon** [comment]
P.S.: I deleted several scenes during migration, which used LockView. Maybe there are still some settings for those scenes and LockView tries to apply these to a missing scene?

**Comment by CDeenen** [comment]
Thanks for the bug report.
Does this error only appear on initialization?
Could you check if the control buttons work?

**Comment by sanguaire** [comment]
The buttons are working. It's only during the initialization phase.

**Comment by wickermoon** [comment]
Yes, as far as I can see the error messages only appear during initialization.  The buttons work fine.

**Comment by CDeenen** [comment]
I think it's trying to access something before that something is initialized. It's weird that I didn't notice it during testing. But since everything seems to be working, just ignore it for now. I'll try to get it fixed soon.

**Comment by wickermoon** [comment]
Okay, I fixed the bug myself buuuuuuuut I've never worked with a public repository, so how do I do pull requests here on github? Do I push my branch to my own online repo?

**Comment by CDeenen** [comment]
fixed
