### ISSUE TITLE
[BUG] User control of Lock/Pan can not have both set

### ISSUE THREAD

**Issue by mwedel255** [CDeenen/LockView#81]
Thank you for doing the following enhancement: Add ability for players to lock view/pan #78
In playing with this, if I do pan lock it behaves as expected.  However, if I then lock the zoom, zoom is now locked as expected, but once again, the map can pan around.  Likewise, of zoom lock is on, and pan lock is then enabled, zoom lock is cleared.
This is with latest version of Lockview on release 9 of FoundryVTT

**Comment by CDeenen** [comment]
I can't replicate this.
Do you get any errors in the console?

**Comment by mwedel255** [comment]
I just updated to latest foundry (10.285), and am also unable to reproduce, so will close this
