### ISSUE TITLE
[BUG] Lock settings per scene are ignored after Foundry update to 10.285

### ISSUE THREAD

**Issue by r-valyar** [CDeenen/LockView#83]
**Setup**
 - OS: Windows/MacOS
 - Browser: Firefox, MS Edge
 - Module version: 1.5.4
 - Foundry version: 10.285
 - Gaming system & version: Conan 1.7.1
 - Any other modules enabled: yes, but no module is related to scene or canvas controls

**Describe the bug**
After Foundry update this morning to 10.**285**, the lock mechanisms are no longer working and players and GM can freely zoom/pan or interact with scene despite the settings.

**Screenshots**
n/a

**Console Log**

```
Error: You are accessing the Scene#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
```

```
Error: Setting canvas.blurDistance is replaced by setting canvas.blur.strength
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
```

```
Uncaught TypeError: this.updateBlur is not a function
[Detected 1 package: LockView]
```

**Additional context**
I noticed that when I load the world and log in, the active scene is black until I move to another scene and go back.

**Comment by shorax** [comment]
I would just like to add I get the same error. With the same outcome.
Changes from above: 
Browser: Chrome
Game System: DnD 5e 2.0.2

**Comment by TheEpicSnowWolf** [comment]
Having the same console errors here, but instead of the lock just not applying as a result, I'm getting a completely black scene.

**Comment by wickermoon** [comment]
See #82 with 10.285, foundry changed their API and accidentally made a mistake on their part.
If you don't want to wait for a foundry update, you can fix it yourself, by replacing this.updateBlur with canvas.updateBlur in the foundry.js file.

**Comment by CDeenen** [comment]
I'll try to push an update to fix this later today

**Comment by CDeenen** [comment]
A bit later than planned, but this should be fixed in the latest release
