### ISSUE TITLE
[BUG] Lock View not working on Player side + Players can see GM Mouse Cursor when setting disabled

### ISSUE THREAD

**Issue by cineasteroid** [CDeenen/LockView#84]
**Setup**
 - OS: Win11
 - Browser: Chrome
 - Module version: 1.5.4
 - Foundry version: v9
 - Gaming system & version: The One Ring 2e
 - Any other modules enabled: No

**Describe the bug**
Despite working and showing properly on the GM side, the Lock View settings seem to not affect the canvas for the Players. For example, if I lock Pan and Zoom as the GM, it presents and works as intended on the GM's screen; however, logging in as a player, I am able to pan and zoom the canvas at will.

Additionally, Players are able to see a "phantom" mouse cursor from the GM, despite this setting being turned off for all. This cursor does not move in correspondence to the GMs mouse. Can confirm that this only occurs when Lock View module is enabled.

**Screenshots**
(From Player's point-of-view)
![lock-view-bug](https://user-images.githubusercontent.com/113319516/189558642-1ebfd439-a1c0-4173-9d53-a85ca429b493.png)

**Console Log**
No console log errors.

**Additional context**
For context, I am only having this issue in my TOR2e world and not in my DnD5e world, so it may be a system-centric issue.

**Comment by cineasteroid** [comment]
Closing-- was able to fix myself. Forgot about user-specific configurations!

**Comment by victor-am** [comment]
@cineasteroid can you explain how you fixed it? I'm having the same issue.
