### ISSUE TITLE
[FEATURE] Copy scene settings to another scene or all scenes

### ISSUE THREAD

**Issue by CDeenen** [CDeenen/LockView#86]
Add buttons in the scene config:
Copy: copy scene's settings
Paste: paste the copied settings to the scene
Apply to all: Apply this scene's settings to all scenes

**Comment by marshallharck** [comment]
Don't know if this will help. but in looking for something to assist me with this, I got a very helpful macro from Zhell#9201 and Freeze#2689 in the Foundry discord.

for(const scene of game.scenes) {
  await scene.setFlag("LockView", "autoScale", 5);
  await scene.setFlag("LockView", "lockPan", true);
  await scene.setFlag("LockView", "lockZoom", true);
  await scene.setFlag("LockView", "lockPanInit", true);
  await scene.setFlag("LockView", "lockZoomInit", true);
}

**Comment by CDeenen** [comment]
Added a Scene Configurator in the latest release that allows easy configuration of scene settings, including copying and pasting
