### ISSUE TITLE
Lockview pushing scene navigation bar off the left side of the map

### ISSUE THREAD

**Issue by Tatonker** [CDeenen/LockView#89]
**Setup**
 - OS: Ubuntu
 - Browser: Chrome
 - Module version: 1.5.5
 - Foundry version: 10.291
 - Gaming system & version: [e.g. dnd5e 1.3.3]
 - Any other modules enabled: Find the Culprit only

**Describe the bug**
When using Lockview and hiding UI elements on sidebar collapse (except for navigation bar), the navigation bar is pushed off the left hand side of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/70360365/205521626-c57cc8ee-599f-463d-99ce-d10b62740a85.png)

**Console Log**
There are no issues in the console log that I can identify as being related to Lockview.

**Additional context**

**Comment by CDeenen** [comment]
Thanks for the bug report. I can replicate this issue and I'll look into fixing this.
