### ISSUE TITLE
[FEATURE] Button to remove the Lock View control from the left toolbar

### ISSUE THREAD

**Issue by apoapostolov** [CDeenen/LockView#94]
Currently Hide Control Button doesn't seem to do this.

**Comment by Altrix1** [comment]
Yes.  
When I use "User Configuration" the control button on the left side - it's always visible

<img width="473" alt="image" src="https://user-images.githubusercontent.com/86872105/221188421-15a3f7ca-0342-48ca-888b-503daf790f3e.png">
