### ISSUE TITLE
[FEATURE] Expand Sidebar on Load

### ISSUE THREAD

**Issue by CyricPL** [CDeenen/LockView#95]
As a counterpart to the existing option to collapse the sidebar when a specific scene loads, it would also be helpful to be able to go in the other direction and expand the sidebar when a scene loads. This way, if you have one locked scene where your default expectation is an open sidebar, but another that forces it to collapse, players wouldn't have to individually click to restore the sidebar during scene changes.

**Comment by CDeenen** [comment]
I've just released an update where I've changed the 'collapse sidebar' checkbox into a selection where you can choose to collapse or expand the sidebar, or do nothing to the sidebar.
