### ISSUE TITLE
[BUG] Error Message when closing or saving Scene Configuration screen:

### ISSUE THREAD

**Issue by GambetTV** [CDeenen/LockView#99]
Most updated version of v10 and DnD5e v2.2.1, when I go into the Configure Scene options for any scene I am presently viewing (the scene doesn't need to be Activated, but you need to be viewing that scene at least, I get the following error in the console when I close it, regardless of if I X out of it or hit Save:

sceneConfig.js:275 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'tools')
[Detected 1 package: LockView]
    at closeSceneConfig (sceneConfig.js:275:75)

**Comment by CDeenen** [comment]
I can confirm that this happens under some circumstances. I have already fix it in my local build, so it will be in the next update

**Comment by GambetTV** [comment]
There's an issue with the update. "Metadata validation failed for module LockView. The file css/style.css included by module lockview does not exist."

**Comment by CDeenen** [comment]
You're right, I made a stupid mistake and forgot to add the css folder to the release.
I just uploaded a new version which should (hopefully) work.
